version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: monthly
      time: "06:00"
      timezone: America/Chicago
    groups:
      routine-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: ci
      include: scope
