name: Build and publish dev

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      upstream-ref:
        required: false
        type: string

jobs:
  build-and-publish-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      BEETS_VERSION: "2.5.1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          label: 'dev'
          repos: |
            ghcr.io/treyturner/beets
            docker.io/treyturner/beets
          upstream-ref: ${{ inputs.upstream-ref || format('v{0}', env.BEETS_VERSION) }}

      - name: Test
        uses: ./.github/actions/test
        with:
          image-ref: ${{ steps.build.outputs.primary-ref }}
          beets-version: ${{ env.BEETS_VERSION }}

      - name: Publish
        uses: ./.github/actions/publish
        with:
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ github.token }}
          refs: ${{ steps.build.outputs.refs }}
