name: Build and publish dev

on:
  push:
    branches: [main]
  pull_request:
    types: ['open', 'synchronize']

jobs:
  build-and-publish-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and publish
        uses: ./.github/actions/build-and-publish
        with:
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ github.token }}
          label: ${{ github.event_name == 'push' && 'dev' || format('pr{0}', github.event.pull_request.number) }}
          repos: ${{ github.event_name == 'push' && format('{0}\n{1}', 'ghcr.io/treyturner/beets', 'docker.io/treyturner/beets') || '' }}
          upstream-ref: v2.5.1
